{{- $releaseName := .Release.Name -}}
{{- $chartName := include "ingestion-trigger.name" . -}}
{{- $deploymentName := include "deployment.fullname" . }}
{{- $configmapName := include "configmap.fullname" . }}
{{- $cloudProviderFlavor := include "ingestion-trigger.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "ingestion-trigger.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "ingestion-trigger.cloudProviderImagePullSecretName" . -}}
{{- $fs := (include "common.fs.merged" .) | fromYaml }}
{{- $imageTag := include "ingestion-trigger.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "ingestion-trigger.environment" . }}
    release: {{ $releaseName }}
    {{- include "ingestion-trigger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "ingestion-trigger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "ingestion-trigger.selectorLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.resetOnConfigChange }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.env.metrics.enabled }}
        prometheus.io/port: {{ .Values.env.metrics.prometheus.port | quote }}
        prometheus.io/scrape: {{ .Values.env.metrics.prometheus.scrape | quote }}
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      containers:
        - name: {{ $chartName }}
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          {{- end }}
          volumeMounts:
          {{- if $fs.ingestionSourcePvc.enabled }}
            - name: ingestion-storage
              mountPath: /layerSources
              {{- if $fs.ingestionSourcePvc.subPath }}
              subPath: {{ $fs.ingestionSourcePvc.subPath }}
              {{- end }}
          {{- end }}
            {{- if .Values.global.ca.secretName }}
            - mountPath: {{ printf "%s/%s" .Values.global.ca.path .Values.global.ca.key | quote }}
              name: root-ca
              subPath: {{ quote .Values.global.ca.key }}
            {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            {{- if .Values.global.ca.secretName }}
            - name: REQUESTS_CA_BUNDLE
              value: {{ printf "%s/%s" .Values.global.ca.path .Values.global.ca.key | quote }}
            - name: NODE_EXTRA_CA_CERTS
              value: {{ printf "%s/%s" .Values.global.ca.path .Values.global.ca.key | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ $configmapName }}
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.env.targetPort }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
      volumes:
        {{- if .Values.global.ca.secretName }}
        - name: root-ca
          secret:
            secretName: {{ .Values.global.ca.secretName }}
        {{- end }}
        {{- if $fs.ingestionSourcePvc.enabled }}
        - name: ingestion-storage
          persistentVolumeClaim:
            claimName: {{ quote $fs.ingestionSourcePvc.name }}
        {{- end }}
{{- end -}}
