global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: ''
  serviceUrls:
    mapproxyApi: ""
    catalogManager: ""
    jobManager: ""
  jobManagement:
    jobDomain: RASTER
    tasks:
      initTaskType: ""
    ingestion:
      new: 
        jobType: ""
      update: 
        jobType: ""
      updateSwap:
        jobType: ""
  storage:
    fs:
      ingestionSourcePvc:
        enabled: false
        name: ""
        subPath: ""
  ca:
    secretName: ''
    path: '/usr/local/share/ca-certificates'
    key: 'ca.crt'
  ingress:
    domain: 'apps.aroapp.io'        

enabled: true
environment: development
replicaCount: 1
revisionHistoryLimit: 5 # Amount of revisions we keep
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true
imagePullPolicy: Always

serviceUrls:
  mapproxyApi: ""
  catalogManager: ""
  jobManager: ""
jobManagement:
  jobDomain: ""
  tasks:
      initTaskType: ""
  ingestion:
    new: 
      jobType: ""
    update: 
      jobType: ""
    updateSwap:
      jobType: ""

storage:
  fs:
    ingestionSourcePvc:
      enabled: false
      name: ""
      subPath: ""


cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: 'my-registry-secret'
  flavor: openshift

image:
  repository: ingestion-trigger
  tag: 'latest'

nameOverride: ""
fullnameOverride: ""

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

podAnnotations: {}

extraVolumes: []

extraVolumeMounts: []

extraEnvVars: []

command: []
args: []
# command: [ "/bin/sh", "-c", "--" ]
# args: [ "while true; do sleep infinity; done;" ]

sidecars: []


caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'


env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  storageExplorer:  
    layerSourceDir: '/layerSources'
    displayNameDir: "\\layerSources"
    watchDirectory: 'watch'
    validFileExtensions: 
    - 'gpkg'
  validationValuesByInfo:
    crs: 
    - 4326
    fileFormat: 
    - 'GPKG'
    tileSize : 256
    resolutionFixedPointTolerance: 12
    extentBufferInMeters: 50   
  disableHttpClientLogs: false     
  httpRetry:
    attempts: 5
    delay: exponential
    resetTimeout: true  
     

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  path: /
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)

ingress:
  enabled: false
  type: 'nginx-org' # supported values: 'nginx-org' | 'nginx-kubernetes'
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
